kind: pipeline
name: image-linux-amd64
platform:
  os: linux
  arch: amd64

steps:
- name: docker-build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: "rancher/istio-installer"
    tag: "dev"
    dry_run: true

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: "rancher/istio-installer"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

---

kind: pipeline
name: image-linux-arm64
platform:
  os: linux
  arch: arm64

steps:
- name: docker-build
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: "rancher/istio-installer"
    tag: "dev"
    dry_run: true

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    repo: "rancher/istio-installer"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

---

kind: pipeline
name: image-manifest
steps:
- name: docker-manifest
  image: plugins/manifest
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: "rancher/istio-installer:${DRONE_TAG}"
    template: "rancher/istio-installer:${DRONE_TAG}-ARCH"
    platforms:
      - linux/amd64
      - linux/arm64
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- image-linux-amd64
- image-linux-arm64
