name: Build and Push to Docker Hub

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      imageTag:
        description: Base Image Tag (before the :)
        type: string
        required: false
        default: rancher/istio-installer

jobs:
  build-and-push:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get dockerhub username and password from vault
        if: ${{ github.repository == 'rancher/istio-installer' }}
        uses: rancher-eio/read-vault-secrets@main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials username | DOCKER_USERNAME ;
            secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME || secrets.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD || secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ inputs.imageTag }}:${{ github.ref_name }}
